package com.sk89q.bukkit.util.mappings.pnx.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
public enum ChemistryTableType {
    COMPOUND_CREATOR,

    ELEMENT_CONSTRUCTOR,

    LAB_TABLE,

    MATERIAL_REDUCER
}
