package com.sk89q.bukkit.util.mappings.pnx.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
public enum Damage {
    UNDAMAGED,
    SLIGHTLY_DAMAGED,
    VERY_DAMAGED,
    BROKEN;

    public Damage next() {
        return values()[this.ordinal() + 1];
    }
}
