package com.sk89q.bukkit.util.mappings.pnx.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 *
 * Placeholder，use {@link cn.nukkit.math.BlockFace}
 * @author daoge_cmd
 */
@Deprecated
public enum MinecraftBlockFace {
}
