blank_issues_enabled: false
contact_links:
  - name: FAWE 1.15+ Issue Tracker
    url: https://github.com/IntellectualSites/FastAsyncWorldEdit/issues
    about: Click here to move to our new issue tracker, DO NOT USE THIS ONE! YOUR ISSUE WILL BE IGNORED!!!